### ISSUE TITLE
Comparison to Durand-Kerner method

### ISSUE THREAD

**Issue by mikolalysenko** [scijs/poly-roots#2]
Out of some curiosity would like to see how the Durand-Kerner method compares to this technique.

https://www.npmjs.com/package/durand-kerner

**Comment by rreusser** [comment]
Haha, oh man, I'd like to see that too. I'm not sure I'd have implemented this if I'd seen that module. Huh. It'd be nice if Github's organization search feature searched the descriptions as well as the titles.

Hmm… Very interesting… Looks like it's Newton's method-based. I wonder how robust it is in different corner cases like clusters of roots. I was intrigued by the fact that Jenkins-Traub is basically designed for numerical robustness and efficiency, but Durand-Kerner looks pretty ridiculously simple. Reading up, sounds like maybe convergence for D-K is sub-quadratic around roots with multiplicity since it's Newton iteration based…

The application I'm going for basically sweeps over a whole parameter space and requires tons and tons of roots of moderate-order polynomials with—in one place or another—closely spaced roots, but I'm pretty sure implementing this was a moderately silly exercise. Frankly, got halfway through and just wasn't willing to give up. Informative though.

**Comment by rreusser** [comment]
Hmm… wait, does D-K also require a guess, or does it always default to powers of 0.4 + 0.9i? That was one of the plusses of Jenkins-Traub since if you sweep over enough cases, bad guesses tend to get exposed.

Edit: Oh. Guess optional. I didn't scroll over far enough.

**Comment by rreusser** [comment]
Haha, based on the benchmarks, hard to say. The companion matrix method might be the best in general. My time probably would've been better spent working on an ndarray eigenvalue algorithm. As for the benchmarks, I checked them for accuracy but I need to come up with precise error estimates. It's just a little tricky since D-K, for example, located the same root three times instead of three distinct roots. I played with the parameters but didn't have great luck. So premature and possibly incorrect conclusions:

**Jenkins-Traub**: Slow. Maybe buggy. Seems incorrect convergence criteria.
**Durand-Kerner**: Very fast. Struggles with closely spaced roots.
**Companion Matrix**: Not perfect, but pretty good overall.

```
Jenkins-Traub:
                                              z - 6:    0.24215ms
                                            2z - 12:    0.18645ms
                                             z - 6i:    0.11229ms
                                       z^2 + 2z - 3:    0.23441ms
                                            z^2 + 1:    0.22790ms
                                 z^3 - 4z^2 + z + 6:    0.41224ms
  (z-1) * (z+1) * (z + 1 + 1e-4i) * (z + 1 - 1e-4i):    0.45577ms
                                 z^3 - 4z^2 + z + 6:    0.23829ms
                   z^3 - (4+i)z^2 + (1+i)z + (6+2i):    0.35737ms
         1000000 * z^3 - (4+i)z^2 + (1+i)z + (6+2i):    0.45880ms
(z-1)(z-2)(z-3)(z-4)(z-5)(z-6)(z-7)(z-8)(z-9)(z-10):    0.84176ms
                                z^20 + i * z^10 + 1:         ---- [1]


Durand-Kerner:
                                              z - 6:   0.015785ms
                                            2z - 12:   0.025671ms
                                             z - 6i:  0.0030435ms
                                       z^2 + 2z - 3:   0.054323ms
                                            z^2 + 1:   0.089162ms
                                 z^3 - 4z^2 + z + 6:   0.022030ms
  (z-1) * (z+1) * (z + 1 + 1e-4i) * (z + 1 - 1e-4i):   0.040660ms [2]
                                 z^3 - 4z^2 + z + 6:   0.014736ms
                   z^3 - (4+i)z^2 + (1+i)z + (6+2i):   0.018432ms
         1000000 * z^3 - (4+i)z^2 + (1+i)z + (6+2i):   0.022398ms
(z-1)(z-2)(z-3)(z-4)(z-5)(z-6)(z-7)(z-8)(z-9)(z-10):         ---- [3]
                                z^20 + i * z^10 + 1:    0.12316ms


Companion Matrix:
                                              z - 6:   0.046543ms
                                            2z - 12:   0.065213ms
                                             z - 6i:   0.060691ms
                                       z^2 + 2z - 3:   0.029567ms
                                            z^2 + 1:   0.090827ms
                                 z^3 - 4z^2 + z + 6:    0.58734ms
  (z-1) * (z+1) * (z + 1 + 1e-4i) * (z + 1 - 1e-4i):    0.73659ms
                                 z^3 - 4z^2 + z + 6:    0.10034ms
                   z^3 - (4+i)z^2 + (1+i)z + (6+2i):    0.43496ms
         1000000 * z^3 - (4+i)z^2 + (1+i)z + (6+2i):    0.87664ms
(z-1)(z-2)(z-3)(z-4)(z-5)(z-6)(z-7)(z-8)(z-9)(z-10):         ---- [3]
                                z^20 + i * z^10 + 1:    0.10956ms
```
[1] Failed to converge or even exit. I need to debug the convergence criteria.
[2] Durand-Kerner seems to fail pretty unpleasantly for the polynomial `(z-1) * (z+1) * (z + 1 + 1e-4i) * (z + 1 - 1e-4i)`. It's not shocking, I guess, since the roots are closely spaced around z = -1. For this polynomial:
```
J-T: -1.000000024466876   4.859708796419875e-9
     -0.9999999877676417 -0.00010000243274177047
     -0.9999999877654824  0.00009999757303299284
      1                  -1.8783802638311364e-17

D-K: -1.0003572422530556  0.00006735391034094387
     -1.0003572422530556  0.00006735391034094387
     -1.0003572422530556  0.00006735391034094387
      1                  -4.020349042960633e-17

Companion:
     
     -1.000000028348578  -0.00010000001190857904
     -1.0000000283485777  0.00010000001190857907
     -0.9999999433028477  0
      0.9999999999999984  0
```

[3] Returned NaN for all zeros.

**Comment by rreusser** [comment]
Sorry, benchmarked but there was a bit more subtlety to it… still working on straightening things out… The short version:

**D-K**: fast. struggles with closely spaced roots, e.g. `(z-1) * (z+1) * (z + 1 + 1e-4i) * (z + 1 - 1e-4i)`
**J-T**: slow. good precision overall but currently failing on a 20th order polynomial. convergence criteria needs debugging.
**Companion**: Good overall, but about three decimal places of precision on `(z-1)(z-2)(z-3)(z-4)(z-5)(z-6)(z-7)(z-8)(z-9)(z-10)`.

**Comment by mikolalysenko** [comment]
The companion matrix method is probably not performing well due to the poor implementation of QR factorization in numeric.js.  I think if we had a better eigen decomposition routine it might be more competitive/accurate.

Long term though, always nice to have more modules to solve a given problem.  I think having some options here is good since it allows users to trade accuracy for performance in various cases.

**Comment by rreusser** [comment]
Agreed! (Nitpick: QR factorization != QR algorithm, and it's the QR algo that's suffering maybe?)

Yeah, the results are actually turning out to be rather interesting. Getting error estimates and will post results/repo.

**Comment by rreusser** [comment]
I got a little sidetracked on a couple issues because there appears to be a case in which the companion matrix method loses all digits of precision, and a case in which it's pretty precise but (perhaps) totally inaccurate (see: scijs/companion-roots#1 ). This might be a case of that geometric vs. algebraic multiplicity stuff I can never keep straight with eigenvalues, or it might be something else entirely. Or I could be totally wrong.

The Durand-Kerner method is blazing fast. Except it struggles with closely spaced roots as in case 6. Otherwise it's pretty outstanding, but I suspect maybe there are robustness issues including sensitivity to initial guesses (perhaps a red flag for black box solvers) (and maybe scaling issues — like how do you choose good guesses for roots that span orders of magnitude? does it lose lots of precision in these cases?) that prevent it from being the go-to method for these things.

Jenkins-Traub brings up the rear on timing, at least until you get to large problems. It chugs along pretty respectably and doesn't fall over in these cases, although I'm sure there are plenty of corner cases where it could struggle. Its strength is in needing no input and proceeding from the smallest roots so that precision isn't lost.

An interesting note:

D-K chokes pretty badly on case 6, returning:

```
1 -7.981039600486516e-18
-0.9999887619012027 0.00038412524677635475
-0.9999887619012027 0.00038412524677635475
-0.9999887619012027 0.00038412524677635475
```

for the four roots. Technically it achieves four digits of precision, but it'd be interesting to see what the threshold is for roots snapping to numerically identical.

Okay, here are some numbers:

```
                        Method                Time               Error

1)  z - 6:
                 Jenkins-Traub          0.18021 ms         0.00000e+00
                 Durand-Kerner          0.01288 ms         2.22045e-16
              Companion Matrix          0.06486 ms         0.00000e+00

2)  z^2 + 1:
                 Jenkins-Traub          0.25117 ms         1.07203e-18
                 Durand-Kerner          0.04905 ms         0.00000e+00
              Companion Matrix          0.84850 ms         3.14208e-16

3)  z^2 + 2z - 3:
                 Jenkins-Traub          0.17595 ms         1.08792e-22
                 Durand-Kerner          0.04448 ms         5.88876e-17
              Companion Matrix          0.15792 ms         1.35064e-15

4)  z^3 - 4z^2 + z + 6:
                 Jenkins-Traub          0.29488 ms         6.43045e-21
                 Durand-Kerner          0.02057 ms         2.31972e-16
              Companion Matrix          0.50635 ms         3.51259e-15

5)  z^3 - (4+i)z^2 + (1+i)z + (6+2i):
                 Jenkins-Traub          0.21368 ms         2.65217e-16
                 Durand-Kerner          0.00407 ms         1.24919e-16
              Companion Matrix          0.38835 ms         1.41421e+00

6)  (z-1) * (z+1) * (z + 1 + 1e-4i) * (z + 1 - 1e-4i):
                 Jenkins-Traub          0.35790 ms         3.05511e-08
                 Durand-Kerner          0.02325 ms         6.90018e-04
              Companion Matrix         29.76010 ms         6.79238e-08

7)  (x-1000000)*(x+%i)*(x-%i):
                 Jenkins-Traub          0.19570 ms         7.58889e-19
                 Durand-Kerner          0.00867 ms         3.83997e-11
              Companion Matrix          0.53090 ms         7.01365e-10

8)  (z-1)(z-2)(z-3)(z-4)(z-5)(z-6)(z-7)(z-8)(z-9)(z-10):
                 Jenkins-Traub          0.83523 ms         4.45072e-10
                 Durand-Kerner          0.17730 ms         3.32534e-10
              Companion Matrix         18.65999 ms         1.41236e+00

9)  z^20 + i * z^10 + 1:
                 Jenkins-Traub          2.23841 ms
                 Durand-Kerner          0.13878 ms
              Companion Matrix         64.20926 ms
```

**Comment by rreusser** [comment]
Source (sloppy; sorry): https://github.com/rreusser/scijs-polynomial-roots-comparison

**Comment by rreusser** [comment]
Marking closed since I think that's a reasonable comparison. Solving problems is a different matter. :smile:
